[package]
name = "shape-z"
edition = "2024"
version = "0.8.23"
license = "MIT"
authors = ["Markus Moenig"]
description = "An Voxel editor and renderer."

[[bin]]
name = "forgedthoughts"
path = "src/main.rs"

[dependencies]

theframework = { version = "0.1.40", git = "https://github.com/markusmoenig/TheFramework", features = [
    "ui",
], default-features = true }
# theframework = { path = "../TheFramework", features = [
#     "ui",
# ], default-features = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vectorize = "0.2.0"
rust-embed = { version = "8", default-features = true, features = [
    "include-exclude",
] }
rayon = "1"
png = "0.17"
open = "5.0.1"
fontdue = "0.9.3"
self_update = { version = "0.39.0", features = [
    "archive-tar",
    "compression-flate2",
] }
indexmap = { version = "2", features = ["serde"], default-features = true }
vek = { version = "0.17.1", default-features = true }
regex = "1.11.1"
arboard = "3.4.1"
toml = "0.8.20"
# lazy_static = "1.5.0"
rand = "0.9"
num_cpus = "1.16.0"

[package.metadata.bundle.bin.eldiron]
name = "Eldiron"
identifier = "com.moenig.eldiron"
icon = ["../build/Eldiron.icns"]
resources = []
copyright = "Copyright (c) Markus Moenig 2025. All rights reserved."
category = "Game"
short_description = "A game creator for classical RPGs with modern features."
long_description = """
Create classical RPGs with Eldiron.
"""

# [lib]
# name = "rustapi"
# crate-type = ["staticlib"]

[patch.crates-io]
radium = { version = "1.1.0", git = "https://github.com/youknowone/ferrilab", branch = "fix-nightly" }
